version: 0.2

env:
  variables:
    key: "S3_BUCKET"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g newman
      - yum install -y jq

  pre_build:
    commands:
      - echo "Copying environment and collection files from S3..."
      - aws s3 cp "s3://${S3_BUCKET}/postman-env-files/PetStoreAPIEnvironment.postman_environment.json" ./02postman/
      - aws s3 cp "s3://${S3_BUCKET}/postman-env-files/PetStoreAPI.postman_collection.json" ./02postman/
      - cd ./02postman
      - ./update-postman-env-file.sh
      - echo "Listing files in ./02postman"
      - ls -l

  build:
    commands:
      - echo "Starting Newman tests..."
      - newman run PetStoreAPI.postman_collection.json --environment PetStoreAPIEnvironment.postman_environment.json -r junit --verbose --reporter-junit-export ./newman/results.xml

reports:
  JUnitReports:
    files:
      - '**/*'
    base-directory: '02postman/newman'
